### ISSUE TITLE
P-S not properly parsing difference in `record_in_processes`

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#225]
See https://github.com/mozilla/mozilla-schema-generator/issues/147

[Here](https://phabricator.services.mozilla.com/D78033) is where this field was added, and [here](https://phabricator.services.mozilla.com/D89401) is where it changed. The probe-info-service should have an entry for each of those, but instead it only has an entry for the latter.

**Comment by Ben-Wu** [comment]
Looks like https://phabricator.services.mozilla.com/D87303 is where the relevant probes were added (suffixed with `_tm`).  Adding here for posterity.

**Comment by Ben-Wu** [comment]
From what I can see, the history of each probe is one entry per major version and not per revision.  Since this probe was added and changed in the same version, probe info service will only have the latest information in the current version.  The probe comparison code looks fine.

So a solution is to use every revision we get from buildhub instead of just the ones from https://hg.mozilla.org/mozilla-central/json-tags.  This looks feasible to me since we already fetch all the relevant data.

@fbertsch is that correct and is this solution ok?

**Comment by fbertsch** [comment]
Wow, I thought we had removed that awhile ago. Indeed the best case here would be to drop using `json-tags` at all and get everything from buildhub.
