### ISSUE TITLE
probe-info-service showing `migration_telemetry_identifiers_fennec_client_id` as expired in 2020

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#272]
Going to probe-info-service for support-migration, it shows the fennec_client_id as having expired already: https://probeinfo.telemetry.mozilla.org/glean/support-migration/metrics

We would expect that to match the version in the current metrics.yaml file: https://github.com/mozilla-mobile/android-components/blob/master/components/support/migration/metrics.yaml

This discrepancy must be arising during the scraping.

**Comment by wlach** [comment]
Looking at this a bit. @Iinh's work on adding historical references to each metric continues to pay dividends.

probeinfo specifies latest version of file as: https://github.com/mozilla-mobile/android-components/blob/de1f46edbf9ac27f7fa680130d361043eccce10c/components/support/migration/metrics.yaml#L33

but there have been a number of changes since then:

https://github.com/mozilla-mobile/android-components/blame/65cbf6f99e12ef668a4b3965c4e3c14fe545c233/components/support/migration/metrics.yaml#L39

Will dig in deeper.
