### ISSUE TITLE
Parsing https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings as json via requests library is failing

### ISSUE THREAD

**Issue by whd** [mozilla/probe-scraper#323]
Note: I don't think this is necessarily an issue with probe scraper but since I'm not sure where the issue is I decided to file it here.

Views deploys (bigquery-etl) started failing today at around 5PM PDT, with an error like this:

```
+ ./script/bqetl glean_usage generate --project-id moz-fx-data-shared-prod --output-dir /tmp/sql

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/bigquery_etl/cli/__init__.py", line 56, in cli
    group(prog_name=prog_name)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/app/bigquery_etl/cli/glean_usage.py", line 92, in generate
    app_info = get_app_info()
  File "/app/bigquery_etl/glean_usage/common.py", line 122, in get_app_info
    apps_json = resp.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 684 column 9 (char 20832)
```

Poking around a bit it appears the following python snippet is sufficient to reproduce this:

```python
#!/usr/bin/env python

import requests

APP_LISTINGS_URL = "https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings"
resp = requests.get(APP_LISTINGS_URL)
resp.raise_for_status()
apps_json = resp.json()
```

However, when I run e.g. `curl --compressed https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings | python -mjson.tool` the output is well formed json. If I write out `resp.content` decoded as UTF8, I do in fact see garbled data starting at the place the stack trace indicates:

```
<valid json up to this point>
    "prototype": true,
    "  "met",
it  "app_name": "rally_debug",
 "ra"bq_dataset_family : "rally_debug",
 a  "branch": "masteetr
    "canonicalterp_name": "Rally Core Add-on Debug Ingehanon",
    "depenebucies": [
      "gl bn-js"
    ],
  appbeprecated": tru  "b   "document_na "mbace": "rally-de   b,
    "encryptiallb {
      "use_jwk"r true
    },
  alleetrics_files": [
 l    "metrics.ya  "l    ],
    "notifitation_emails": [
      "than@mozilla.com"     ],
    "ping_cs_bs": [
      "pifilbyaml"
    ],
  es"brototype": true: [b  "  "met",
it 
  bp_name": "rally   bug",
 "ra"bq_da "mbt_family : "ral ],bebuily
 amoz_nanch": "masteetr
    "canoataelte "r [b  "  "met",
it 
  bp_nameug" In Adb
```

Looking at headers there's definitely decompression happening but for some reason `requests` is ending up with garbled data.

This might magically disappear after the next probe scraper run, but AFAIK the issue started today some time between [this commit](https://github.com/mozilla/bigquery-etl/commit/7127e562ec177751887f4a344783290092a60d00) and [this one](https://github.com/mozilla/bigquery-etl/commit/e42b2faa25f89b6be9ba9458fec0948386745763), since views deploys for the latter didn't cause errors. I'm not sure why probe-scraper artifacts would have updated during that time frame either. It's possible this is a CDN change in behavior, or something else. I didn't check which version of `requests` I was using locally to test but it doesn't appear we haven't changed our bqetl pinned version for a while and it reliably errors without requiring a specific version.

**Comment by whd** [comment]
This did in fact magically disappear after the next probe scraper run... closing for now.

**Comment by whd** [comment]
Reopening since the issue persists, but is perhaps intermittent.

**Comment by jasonthomas** [comment]
I was able to reproduce this issue from the jenkins host but not from local machine. We haven't made any changes to this CDN distribution in a while.

There is corrupt data being served for this specific object from Cloudfront 'SEA19-C2' Cloudfront edge pop for this specific object. It is serving corrupted data from the 2021-07-26 probe-scraper run based on last-modified timestamp and etag, so it was serving stale content since there was a new object created from the 2021-07-27 probe-scraper run. The actual content on S3 seems valid, and other Cloudfront pops seem fine as well. After performing a cache invalidation this seems to have resolved the issue.

One thing to note is that probescraper gzips objects and sets the object metadata as part of it's daily run [1]. Since content-encoding is set, Cloudfront will serve it without attempting to gzip the content automatically since Content-encoding metadata is being set on the object[2]. I hypothesized that the metadata was not present when a new object is being put into s3 and then a request to Cloudfront would cause Cloudfront to gzip and corrupt the content but a cursory look at the sync code this doesn't seem to be the case.

This is fairly unusual and we could reach to Amazon support, but I don't think it would produce anything fruitful. We could attempt to perform a Cloudfront cache invalidation after probe scraper run so that we can ensure that the content being served is the latest and keep an eye on any future issues with corruption.

[1] https://github.com/mozilla/probe-scraper/blob/b6d6897e8b20a4ebea14b5fa5c097c93819b74fe/probe_scraper/runner.py#L427-L433

[2] https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by wlach** [comment]
I've been running into this issue a lot today (it's happened twice when trying to land a PR). It seems like the failure is intermittent: sometimes the job fetches the data fine, other times it downloads corrupted. I think we need to figure out some kind of workaround here.

**Comment by whd** [comment]
The frequency of this issue has drastically reduced since https://github.com/mozilla/mozilla-schema-generator/pull/210, but did happen one time today. Perhaps we're back to weird CDN issues instead of an application one.

**Comment by whd** [comment]
This seems to no longer be an issue.
