### ISSUE TITLE
"Glean probe-scraper" GitHub action timing out

### ISSUE THREAD

**Issue by badboy** [mozilla/probe-scraper#574]
We have at least 2 instances where the action was failing today:

* [bedrock](https://github.com/mozilla/bedrock/actions/runs/4563496742/jobs/8052055356) - `curl: (22) The requested URL returned error: 408 - upstream request timeout`
* [fenix](https://github.com/mozilla-mobile/firefox-android/actions/runs/4563688760/jobs/8052490534?pr=1097) - ` curl: (22) The requested URL returned error: 503 Service Unavailable`

According to @kik-kik the metrics for this cloud function report a spike in execution time today, running into the nine minute cloud function timeout. This used to be well below 5 minutes.
This might be intermittent or it might point to an issue.

**Comment by relud** [comment]
> This might be intermittent or it might point to an issue.

this issue was unrelated to any code changes, and didn't appear any other time in the last 30 days.

I attempted to look at the relevant logs, but none were emitted from the probe scraper code, the only logs were from google logging `Function execution started` and `Function execution took [...] ms, finished with status: 'error'`.

As such I believe this was a transient error that was outside of our control.
